plot([Vins, Vins, Vins], [V4s, V3s, V2s], 'o', 'linewidth', 2)
title('Voltage transfer characteristic for strong inversion V_b', 'fontsize', 15)
xlabel('V_1 (V)', 'fontsize', 13)
ylabel('V_{out} (V)', 'fontsize', 13)
legend('V_2 = 4V', 'V_2 = 3V', 'V_2 = 2V')